sudo: required

services:
  - docker

before_install:
  - docker build -t nexor/telega -f Dockerfile.travisci .
  - docker images

script:
  - docker run -it --rm nexor/telega /bin/bash -c "ldc2 --version && dub test --compiler=ldc2"
  - docker run -it --rm nexor/telega dub build -b debug --compiler=ldc2
  - docker run -it --rm nexor/telega dub build -b release --compiler=ldc2
  - docker run -it --rm nexor/telega /bin/bash -c "ldc2 --version && dub test --compiler=dmd"
  - docker run -it --rm nexor/telega dub build -b debug --compiler=dmd
  - docker run -it --rm nexor/telega dub build -b release --compiler=dmd

notifications:
  email: false
