sudo: required

env:
  - CONFIG=default
  - CONFIG=requests-driver

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run --rm dmd dmd --version
  - docker-compose run --rm ldc ldc2 --version

script:
  - docker-compose run --rm dmd dub test --config=$CONFIG
  - docker-compose run --rm ldc dub build -b release --config=$CONFIG

notifications:
  email: false
