sudo: required

env:
  - CONFIG=default
  - CONFIG=requests-driver

services:
  - docker

before_install:
  - docker-compose run --rm dmd dmd --version
  - docker-compose run --rm ldc ldc --version
  - docker-compose build

script:
  - docker-compose run --rm dmd dub --config=$CONFIG
  - docker-compose run --rm ldc dub --config=$CONFIG

notifications:
  email: false
