sudo: required

env:
  - CONFIG=default
  - CONFIG=requests-driver

services:
  - docker

before_install:
  - docker-compose run -it --rm dmd $COMPILER --version
  - docker-compose run -it --rm ldc $COMPILER --version
  - docker-compose build

script:
  - docker-compose run -it --rm dmd dub --config=$CONFIG
  - docker-compose run -it --rm ldc dub --config=$CONFIG

notifications:
  email: false
