version: '3'

services:
    dmd:
        build:
            context: .
            dockerfile: ./docker/dmd/Dockerfile
        volumes:
            - ./:/src
        command: dmd --version
    ldc:
        build:
            context: .
            dockerfile: ./docker/ldc/Dockerfile
        volumes:
            - ./:/src
        command: ldc2 --version
