version: '3'

services:
    example:
        build:
            context: .
            dockerfile: ./docker/ldc/Dockerfile
        env_file: .env
        volumes:
            - ./:/dlang/app
            - ./.dub:/root/.dub
