version: '3'

services:
    dmd:
        build:
            context: .
            dockerfile: ./docker/dmd/Dockerfile
        volumes:
            - ./:/dlang/app
        command: dmd --version
    ldc:
        build:
            context: .
            dockerfile: ./docker/ldc/Dockerfile
        volumes:
            - ./:/dlang/app
        command: ldc2 --version
    example:
        image: dlang2/ldc-ubuntu
        env_file: .env
        volumes:
            - ./:/dlang/app
            - ./.dub:/root/.dub
